### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by adellibovi** [odigeoteam/TableViewKit#13]

**Comment by adellibovi** [comment]
@ndleon09 I tag this as "Starter Task" for new contributors, agreeing?

**Comment by ndleon09** [comment]
Hi @adellibovi , i was trying to make project compatible with **Swift Package Manager**, but i think it's **not possible**. I have the following error:
**error:** no such module 'UIKit'

Here the discussion about the problem:
http://stackoverflow.com/questions/34778823/swift-package-manager-uikit-dependency
