### ISSUE TITLE
Improve draw performance

### ISSUE THREAD

**Issue by ndleon09** [odigeoteam/TableViewKit#17]
Call the draw method inside **tableView:willDisplayCell:forRowAtIndexPath:** method instead tableView:cellForRowAtIndexPath: method.

Don’t perform data binding at **tableView:willDisplayCell:forRowAtIndexPath:** method, because there’s no cell on screen yet. For this you can use  **tableView:willDisplayCell:forRowAtIndexPath:** method which can be implemented in the delegate of UITableView. The method called exactly before showing cell in UITableView’s bounds.

What do you think?

**Comment by adellibovi** [comment]
I already read that article some time ago and made some research, this is actually a "person thought" and not official by Apple. There were some tests by another article (https://tech.zalando.com/blog/proper-use-of-cellforrowatindexpath-and-willdisplaycell) replying to the one you are quoting that proved that at the moment there is no performance gain.

**Comment by adellibovi** [comment]
Maybe let's leave this issue open for a while if someone can prove that in iOS 10 something changed

**Comment by ndleon09** [comment]
Yeah, at the end of article, the author say:
**Note:** With iOS10, willDisplayCell and cellForRowAtIndexPath call orders will be changed. I will follow up with another article about the changes in iOS10 in the near future.

**Comment by adellibovi** [comment]
Closing this since we don't have any update
