### ISSUE TITLE
Manager is not set replacing equatable items

### ISSUE THREAD

**Issue by gspadaro** [odigeoteam/TableViewKit#27]
This is the scenario: you have two instances of the same type of item which is (in this case) conform to the Equatable protocol and you want to replace using the method items.replace(with:.
Pay attention because the manager of the new Item is properly set but you lose the reference of the old one. If you have some kind of logic in order to use the manager of the old one you will have item?.manager = nil.

**Comment by adellibovi** [comment]
This has been fixed, let me know if you are experience this bug again.
